# devopsdemo - pipeline

name: ($date:yyyyMMdd)$(rev:.rr) #20190910.00

stages:
  - stage: 'build'
    condition: succeeded()
    displayName: 'build-mvc'
    jobs:
      - job:
        condition: succeeded()
        displayName: 'build-process'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - scripts: |
              echo 'build passed...'

  - stage: 'test'
    condition: succeeded('build')
    dependsOn: 
      - build
    displayName: 'test-mvc' 

  - stage: 'pack'
  - stage: 'deploy'

triggers:
  - branches:
      include:
        - master

variables:
